### ISSUE TITLE
Youtube request failure

### ISSUE THREAD

**Issue by Igor-Polatajko** [PNUdev/radio-service-api#28]
**Steps to reproduce:**
1. Go to https://radio-service-api-stage.herokuapp.com/api/v1/videos/recent

**Actual result:**
![image](https://user-images.githubusercontent.com/34420901/88716095-37e67000-d127-11ea-9cea-e05b87660b48.png)

**Expected result:**
We are able to get response from api with data about recent videos.

_Note:_ bug is present only on remote.
**Suggested solution:** add allowed urls (to stage and to prod) from google dev console.

**Comment by volodymyrvynnyk** [comment]
Invalid Youtube channel id was written in Properties vargs
